### ISSUE TITLE
won't compil anymore :/

### ISSUE THREAD

**Issue by tsukasagenesis** [sanderv32/ngx_http_auth_yubikey_module#1]
Hi,

too bad, plugin don't work anymore with nginx 1.4.2 and lastest C client yubikey :/

/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c: In function 'ngx_http_auth_yubikey_otp_handler':
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:306:3: error: pointer targets in passing argument 1 of 'sprintf' differ in signedness [-Werror=pointer-sign]
/usr/include/x86_64-linux-gnu/bits/stdio2.h:32:1: note: expected 'char \* **restrict**' but argument is of type 'u_char _'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:319:2: error: pointer targets in passing argument 1 of 'strlen' differ in signedness [-Werror=pointer-sign]
/usr/include/string.h:399:15: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:319:2: error: pointer targets in passing argument 1 of 'base64_decode_block' differ in signedness [-Werror=pointer-sign]
/usr/local/src/ngx_http_auth_yubikey_module-master/b64/cdecode.h:26:5: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:319:2: error: pointer targets in passing argument 3 of 'base64_decode_block' differ in signedness [-Werror=pointer-sign]
/usr/local/src/ngx_http_auth_yubikey_module-master/b64/cdecode.h:26:5: note: expected 'char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:330:5: error: pointer targets in passing argument 1 of 'strlen' differ in signedness [-Werror=pointer-sign]
/usr/include/string.h:399:15: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:346:5: error: pointer targets in passing argument 1 of 'atoi' differ in signedness [-Werror=pointer-sign]
/usr/include/stdlib.h:284:1: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:346:5: error: pointer targets in passing argument 4 of 'ykclient_set_client' differ in signedness [-Werror=pointer-sign]
/usr/local/include/ykclient.h:72:15: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:350:3: error: pointer targets in passing argument 1 of 'strstr' differ in signedness [-Werror=pointer-sign]
/usr/include/string.h:342:14: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:350:3: error: pointer targets in passing argument 2 of 'strstr' differ in signedness [-Werror=pointer-sign]
/usr/include/string.h:342:14: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:352:4: error: pointer targets in passing argument 1 of 'strstr' differ in signedness [-Werror=pointer-sign]
/usr/include/string.h:342:14: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:352:4: error: pointer targets in passing argument 2 of 'strstr' differ in signedness [-Werror=pointer-sign]
/usr/include/string.h:342:14: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:352:6: error: pointer targets in assignment differ in signedness [-Werror=pointer-sign]
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:353:4: error: pointer targets in passing argument 1 of 'strstr' differ in signedness [-Werror=pointer-sign]
/usr/include/string.h:342:14: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:353:9: error: pointer targets in assignment differ in signedness [-Werror=pointer-sign]
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:354:4: error: pointer targets in passing argument 1 of 'strstr' differ in signedness [-Werror=pointer-sign]
/usr/include/string.h:342:14: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:357:5: error: pointer targets in passing argument 2 of 'ykclient_request' differ in signedness [-Werror=pointer-sign]
/usr/local/include/ykclient.h:111:22: note: expected 'const char *' but argument is of type 'u_char *'
/usr/local/src/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.c:359:5: error: implicit declaration of function 'ykclient_check_signature' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[1]: *_\* [objs/addon/ngx_http_auth_yubikey_module-master/ngx_http_auth_yubikey_module.o] Error 1
make[1]: **\* Waiting for unfinished jobs....

Best regards.

**Comment by sanderv32** [comment]
Hi, the branch "compile-fix" should compile only didn't test if the module works properly.

**Comment by teward** [comment]
Confirmed that the `compile-fix` branch fixes the fail to build, see #2 which has the confirmation of that.   (compiled on Ubuntu 14.04 in that issue.)
