### ISSUE TITLE
[FIXED] [compile-fix branch] 401 Authorization Required return after auth is accepted.

### ISSUE THREAD

**Issue by teward** [sanderv32/ngx_http_auth_yubikey_module#3]
As mentioned in Issue #2, there is an issue with the module where nginx returns 401 Authorization Required after you hit "OK" or the enter key at the authorization window popup.  As a result, you have to hit "F5" or Refresh to reload the page, and then the server recognizes the auth credentials.

Not sure if it's an error in the module or nginx, but it's still an inconvenience.  After you refresh, it works fine, and you don't have to reenter the data.

**Comment by sanderv32** [comment]
Did some changes today and some testing. Seems like it works now. WSApi version is now change too 2.0. Can you test it on your server?

**Comment by teward** [comment]
@sanderv32 Sure, I'm testing in a VM and building in a PPA, so give me a bit to rebuild/recompile/rebase.  I'll let you know.

**Comment by teward** [comment]
@sanderv32 Works as expected!  I authenticated and the system went and did NOT show a 401 error after getting past the prompt!

Thanks for making all these changes!
